#!/usr/bin/env python3
"""render-rules.py — compile rule packs into every coding agent's native dialect.

Six agents want the same rules in six different files, in six different formats,
with six different frontmatter conventions:

  claude    .claude/rules/<domain>.md
  cursor    .cursor/rules/<domain>.mdc                      (MDC: description/globs/alwaysApply)
  windsurf  .windsurf/rules/<domain>.md                     (YAML frontmatter)
  copilot   .github/instructions/<domain>.instructions.md   (applyTo frontmatter)
  codex     AGENTS.md            (managed block)
  gemini    GEMINI.md            (managed block)

Maintaining six copies by hand guarantees drift: someone fixes a rule in
CLAUDE.md, forgets Cursor, and now two agents in the same repo disagree about
what "done" means. So rules are authored ONCE under rules/<domain>/<slug>.md and
compiled here. Rendered files carry a DO-NOT-EDIT banner and are overwritten.

`render-rules.py check` re-renders in memory and diffs against what is on disk,
exiting non-zero on any mismatch. Wire that into CI and drift stops being a thing
you have to remember not to do: it becomes a red build.

Dependency-free by design (stdlib only), matching the rest of scripts/. The
frontmatter parser below handles the strict subset that rules/SPEC.md defines and
REFUSES anything outside it, rather than guessing. A rules file that parses
differently than it reads is worse than one that fails loudly.

CLI:
  render-rules.py list                       # list all rules and their targets
  render-rules.py render                     # render every domain to every agent
  render-rules.py render --domain coding     # one domain
  render-rules.py render --agent cursor      # one agent
  render-rules.py check                      # CI gate: fail if any rendered file is stale

Exit codes:
  0 — success (or: check passed, everything current)
  1 — check failed: at least one rendered file is stale or missing
  2 — usage error
  3 — a rule file is malformed
"""

import argparse
import io
import re
import sys
from pathlib import Path

VAULT_ROOT = Path(__file__).resolve().parent.parent
RULES_DIR = VAULT_ROOT / "rules"

AGENTS = ("claude", "cursor", "windsurf", "copilot", "codex", "gemini")
SEVERITIES = ("blocker", "high", "medium")
SEVERITY_ORDER = {s: i for i, s in enumerate(SEVERITIES)}

BANNER = "GENERATED BY scripts/render-rules.py FROM rules/. DO NOT EDIT BY HAND."


# ── frontmatter ──────────────────────────────────────────────────────────────

class RuleError(Exception):
    pass


def parse_frontmatter(text: str, path: Path):
    """Parse the strict YAML subset defined in rules/SPEC.md.

    Supported: `key: scalar`, `key: [a, b]`, folded `key: >` + indented line,
    and block lists (`key:` then `  - item`). Anything else raises, loudly.
    """
    if not text.startswith("---\n"):
        raise RuleError(f"{path}: missing frontmatter (must start with '---')")
    end = text.find("\n---\n", 3)
    if end == -1:
        raise RuleError(f"{path}: unterminated frontmatter (no closing '---')")

    raw = text[4:end + 1]
    body = text[end + 5:].strip() + "\n"

    # PENDING marks "key seen, value arrives on the following indented line(s)".
    # It must be its own sentinel and not "" — an empty string is a legitimate
    # scalar, and conflating the two makes every block list fail to parse.
    PENDING = object()

    meta = {}
    key = None
    for line in raw.split("\n"):
        if not line.strip() or line.lstrip().startswith("#"):
            continue

        # continuation of a block list or a folded scalar
        if line.startswith((" ", "\t")):
            stripped = line.strip()
            if key is None:
                raise RuleError(f"{path}: indented line with no key: {line!r}")
            current = meta.get(key, PENDING)

            if stripped.startswith("- "):
                if current is PENDING:
                    meta[key] = current = []
                if not isinstance(current, list):
                    raise RuleError(f"{path}: '{key}' mixes scalar and list forms")
                current.append(_scalar(stripped[2:]))
            else:
                if current is PENDING:
                    meta[key] = stripped
                elif isinstance(current, str):
                    meta[key] = (current + " " + stripped).strip()
                else:
                    raise RuleError(f"{path}: cannot fold text into list key '{key}'")
            continue

        if ":" not in line:
            raise RuleError(f"{path}: cannot parse frontmatter line: {line!r}")

        key, _, value = line.partition(":")
        key = key.strip()
        value = value.strip()

        if value in (">", "|", ""):
            meta[key] = PENDING
        elif value.startswith("[") and value.endswith("]"):
            inner = value[1:-1].strip()
            meta[key] = [_scalar(v) for v in inner.split(",") if v.strip()] if inner else []
        else:
            meta[key] = _scalar(value)

    # A key whose continuation never arrived is an empty scalar, not a sentinel.
    for k, v in meta.items():
        if v is PENDING:
            meta[k] = ""

    return meta, body


def _scalar(v: str):
    v = v.strip()
    if len(v) >= 2 and v[0] == v[-1] and v[0] in ("'", '"'):
        return v[1:-1]
    if v == "true":
        return True
    if v == "false":
        return False
    return v


# ── loading ──────────────────────────────────────────────────────────────────

def load_rules(domain_filter=None):
    """Load every rule file, validate it, and return them sorted by severity."""
    if not RULES_DIR.is_dir():
        raise RuleError(f"no rules/ directory at {RULES_DIR}")

    rules = []
    seen_ids = {}
    for path in sorted(RULES_DIR.glob("*/*.md")):
        if path.name == "SPEC.md":
            continue
        meta, body = parse_frontmatter(path.read_text(), path)

        for required in ("id", "domain", "title", "severity", "applies_when"):
            if not meta.get(required):
                raise RuleError(f"{path}: missing required field '{required}'")

        domain = meta["domain"]
        slug = path.stem
        expected_id = f"{domain}/{slug}"
        if meta["id"] != expected_id:
            raise RuleError(
                f"{path}: id is {meta['id']!r} but the file's location implies "
                f"{expected_id!r}. The id must equal <domain>/<filename>."
            )
        if path.parent.name != domain:
            raise RuleError(
                f"{path}: domain is {domain!r} but the file sits in "
                f"{path.parent.name!r}/"
            )
        if meta["severity"] not in SEVERITIES:
            raise RuleError(
                f"{path}: severity {meta['severity']!r} is not one of "
                f"{', '.join(SEVERITIES)}"
            )
        if meta["id"] in seen_ids:
            raise RuleError(f"{path}: duplicate id {meta['id']!r} (also in {seen_ids[meta['id']]})")
        seen_ids[meta["id"]] = path

        agents = meta.get("agents") or list(AGENTS)
        if isinstance(agents, str):
            agents = [agents]
        for a in agents:
            if a not in AGENTS:
                raise RuleError(f"{path}: unknown agent {a!r}; want any of {', '.join(AGENTS)}")

        globs = meta.get("globs") or ["**/*"]
        if isinstance(globs, str):
            globs = [globs]

        rules.append({
            "id": meta["id"],
            "domain": domain,
            "title": meta["title"],
            "severity": meta["severity"],
            "applies_when": " ".join(str(meta["applies_when"]).split()),
            "globs": globs,
            "agents": agents,
            "source": meta.get("source", ""),
            "body": body.strip(),
            "path": path,
        })

    if domain_filter:
        rules = [r for r in rules if r["domain"] == domain_filter]

    rules.sort(key=lambda r: (SEVERITY_ORDER[r["severity"]], r["id"]))
    return rules


def domains_of(rules):
    return sorted({r["domain"] for r in rules})


# ── shared body ──────────────────────────────────────────────────────────────

def _trigger_list(rules) -> str:
    """The trigger index. This is the highest-leverage part of a rendered pack.

    A rule an agent never notices it needs is dead weight, so every pack opens
    with the observable moments that should make the agent stop and look.
    """
    out = io.StringIO()
    out.write("## Stop and check this list when any of these is true\n\n")
    for r in rules:
        out.write(f"- {r['applies_when']} (**{r['title']}**)\n")
    return out.getvalue()


def _rule_bodies(rules) -> str:
    out = io.StringIO()
    for r in rules:
        out.write(f"\n### {r['title']}\n\n")
        out.write(f"`{r['id']}` | severity: **{r['severity']}**\n\n")
        out.write(f"**Applies when.** {r['applies_when']}\n\n")
        out.write(r["body"] + "\n")
        if r["source"]:
            out.write(f"\n*Source: {r['source']}*\n")
    return out.getvalue()


def _pack(domain, rules) -> str:
    n = len(rules)
    blockers = sum(1 for r in rules if r["severity"] == "blocker")
    out = io.StringIO()
    out.write(f"# {domain.title()} Rules\n\n")
    out.write(f"{n} rules ({blockers} blocker). Authored in `rules/{domain}/`.\n\n")
    out.write(_trigger_list(rules))
    out.write(_rule_bodies(rules))
    return out.getvalue()


# ── per-agent renderers ──────────────────────────────────────────────────────

def render_claude(domain, rules) -> tuple:
    text = f"<!-- {BANNER} -->\n\n" + _pack(domain, rules)
    return Path(".claude/rules") / f"{domain}.md", text


def render_cursor(domain, rules) -> tuple:
    globs = sorted({g for r in rules for g in r["globs"]})
    always = any(r["severity"] in ("blocker", "high") for r in rules)
    desc = (
        f"{domain.title()} rules for this repo: "
        f"{len(rules)} rules, "
        f"{sum(1 for r in rules if r['severity'] == 'blocker')} blocker."
    )
    out = io.StringIO()
    out.write("---\n")
    out.write(f"description: {desc}\n")
    out.write("globs:\n")
    for g in globs:
        out.write(f'  - "{g}"\n')
    out.write(f"alwaysApply: {'true' if always else 'false'}\n")
    out.write("---\n\n")
    out.write(f"<!-- {BANNER} -->\n\n")
    out.write(_pack(domain, rules))
    return Path(".cursor/rules") / f"{domain}.mdc", out.getvalue()


def render_windsurf(domain, rules) -> tuple:
    always = any(r["severity"] in ("blocker", "high") for r in rules)
    out = io.StringIO()
    out.write("---\n")
    out.write(f"trigger: {'always_on' if always else 'glob'}\n")
    if not always:
        out.write(f"globs: {','.join(sorted({g for r in rules for g in r['globs']}))}\n")
    out.write(f"description: {domain.title()} rules ({len(rules)} rules)\n")
    out.write("---\n\n")
    out.write(f"<!-- {BANNER} -->\n\n")
    out.write(_pack(domain, rules))
    return Path(".windsurf/rules") / f"{domain}.md", out.getvalue()


def render_copilot(domain, rules) -> tuple:
    globs = sorted({g for r in rules for g in r["globs"]})
    apply_to = ",".join(globs) if globs else "**"
    out = io.StringIO()
    out.write("---\n")
    out.write(f'applyTo: "{apply_to}"\n')
    out.write("---\n\n")
    out.write(f"<!-- {BANNER} -->\n\n")
    out.write(_pack(domain, rules))
    return Path(".github/instructions") / f"{domain}.instructions.md", out.getvalue()


def _managed_block(existing: str, domain: str, payload: str) -> str:
    """Splice `payload` between BEGIN/END markers, preserving everything else.

    AGENTS.md and GEMINI.md are hand-written files that we only partly own.
    Clobbering them would destroy the author's prose, so we own a delimited
    region and nothing more.
    """
    begin = f"<!-- BEGIN render-rules:{domain} -->"
    end = f"<!-- END render-rules:{domain} -->"
    block = f"{begin}\n<!-- {BANNER} -->\n\n{payload.rstrip()}\n{end}"

    has_begin, has_end = begin in existing, end in existing
    if has_begin != has_end:
        # Exactly one marker survives. Someone hand-edited one away. Appending a
        # fresh block here would leave the file with a mismatched pair and a
        # duplicated region, and `check` could then report it "current". Refuse to
        # guess which half to trust; make the human repair the markers.
        missing = end if has_begin else begin
        raise SystemExit(
            f"ERROR: {domain} managed block is corrupt: found "
            f"{'BEGIN' if has_begin else 'END'} but not its pair "
            f"({missing!r}). Restore both markers, or delete both to regenerate."
        )

    if has_begin and has_end:
        pattern = re.compile(
            re.escape(begin) + r".*?" + re.escape(end),
            re.DOTALL,
        )
        return pattern.sub(lambda _: block, existing, count=1)

    sep = "" if existing.endswith("\n\n") or not existing else "\n"
    return f"{existing.rstrip()}\n\n{block}\n" if existing.strip() else f"{block}\n"


def render_codex(domain, rules, existing="") -> tuple:
    return Path("AGENTS.md"), _managed_block(existing, domain, _pack(domain, rules))


def render_gemini(domain, rules, existing="") -> tuple:
    return Path("GEMINI.md"), _managed_block(existing, domain, _pack(domain, rules))


MANAGED_BLOCK_AGENTS = ("codex", "gemini")

RENDERERS = {
    "claude": render_claude,
    "cursor": render_cursor,
    "windsurf": render_windsurf,
    "copilot": render_copilot,
    "codex": render_codex,
    "gemini": render_gemini,
}


def build_outputs(rules, agent_filter=None):
    """Return {relpath: content} for every target. Pure; touches no disk state
    except reading the existing managed-block hosts (AGENTS.md / GEMINI.md)."""
    outputs = {}
    agents = [agent_filter] if agent_filter else list(AGENTS)

    for agent in agents:
        for domain in domains_of(rules):
            subscribed = [r for r in rules if r["domain"] == domain and agent in r["agents"]]
            if not subscribed:
                continue
            if agent in MANAGED_BLOCK_AGENTS:
                rel = Path("AGENTS.md" if agent == "codex" else "GEMINI.md")
                # Chain edits so codex+gemini domains accumulate rather than
                # overwrite each other when several domains render in one pass.
                base = outputs.get(rel)
                if base is None:
                    disk = VAULT_ROOT / rel
                    base = disk.read_text() if disk.exists() else ""
                rel, content = RENDERERS[agent](domain, subscribed, base)
            else:
                rel, content = RENDERERS[agent](domain, subscribed)
            outputs[rel] = content

    return outputs


# ── CLI ──────────────────────────────────────────────────────────────────────

def main(argv=None) -> int:
    parser = argparse.ArgumentParser(prog="render-rules.py",
                                     description=__doc__.split("\n")[0])
    sub = parser.add_subparsers(dest="cmd")

    sub.add_parser("list", help="list all rules")

    p_render = sub.add_parser("render", help="write rendered files")
    p_render.add_argument("--domain")
    p_render.add_argument("--agent", choices=AGENTS)

    p_check = sub.add_parser("check", help="CI gate: fail if any rendered file is stale")
    p_check.add_argument("--domain")
    p_check.add_argument("--agent", choices=AGENTS)

    args = parser.parse_args(argv)
    if not args.cmd:
        parser.print_help()
        return 2

    try:
        rules = load_rules(getattr(args, "domain", None))
    except RuleError as exc:
        print(f"ERR: {exc}", file=sys.stderr)
        return 3

    if not rules:
        print("ERR: no rules found", file=sys.stderr)
        return 3

    if args.cmd == "list":
        for r in rules:
            agents = ",".join(r["agents"])
            print(f"{r['severity']:>7}  {r['id']:<42}  {r['title']}")
            print(f"{'':>7}  agents: {agents}")
        print(f"\n{len(rules)} rules across {len(domains_of(rules))} domain(s).")
        return 0

    outputs = build_outputs(rules, getattr(args, "agent", None))

    if args.cmd == "check":
        stale = []
        for rel, content in sorted(outputs.items()):
            disk = VAULT_ROOT / rel
            if not disk.exists():
                stale.append((rel, "missing"))
            elif disk.read_text() != content:
                stale.append((rel, "stale"))
        if stale:
            print("Rendered rule files are out of date with rules/:\n", file=sys.stderr)
            for rel, why in stale:
                print(f"  {why:<8} {rel}", file=sys.stderr)
            print("\nRun: python3 scripts/render-rules.py render", file=sys.stderr)
            return 1
        print(f"All {len(outputs)} rendered rule files are current.")
        return 0

    for rel, content in sorted(outputs.items()):
        dest = VAULT_ROOT / rel
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(content)
        print(f"wrote  {rel}")

    print(f"\n{len(rules)} rules rendered to {len(outputs)} files.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
